security:
    encoders:
        Caiwen\CoreBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, main]
        in_memory:
            memory:
                users:
                    

        main:
            entity:
                class: Caiwen\CoreBundle\Entity\User


    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        admin_area:
            pattern:    ^/admin/
            form_login:
                check_path: _admin_login_check
                login_path: _admin_login
            logout:
                path:   _admin_logout
                target: _admin_login
            anonymous: ~

        user_area:
            pattern:    ^/
            form_login:
                check_path: _user_login_check
                login_path: _user_login
                username_parameter: _username
                password_parameter: _password
                success_handler: user.login_success_handler
            logout:
                path:   _user_logout
                target: _index
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/faq/add, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }
