security:
    encoders:
        Caiwen\CoreBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    lucups:  { password: kkkk, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_area:
            pattern:    ^/user/
            form_login:
                check_path: _user_login_check
                login_path: _user_login
            logout:
                path:   _user_logout
                target: _index
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        admin_area:
            pattern:    ^/admin/
            form_login:
                check_path: _admin_login_check
                login_path: _admin_login
            logout:
                path:   _admin_logout
                target: _admin_login
            anonymous: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
